development:
  key:    "7Dy6Ewtg10d8XbDg"
  secret: "Y8A5D2wclrmiwZqqnBTCIKPz8bJT6QOl"
  url:    "http://ruby_general_admin.dev/"
  callback: "http://ruby_general_admin.dev/syncs/netease/callback"
production:
  key:    "7Dy6Ewtg10d8XbDg"
  secret: "Y8A5D2wclrmiwZqqnBTCIKPz8bJT6QOl"
  url:    "http://admin.nowapp.cn/"
  callback: "http://admin.nowapp.cn/syncs/netease/callback"
