development:
  key:    "801383163"
  secret: "b2d3177bfcd01fc97fe667c273b8a43d"
  url:    "http://ruby_general_admin.dev/"
  callback: "http://ruby_general_admin.dev/syncs/qq/callback"
production:
  key:    "801383163"
  secret: "b2d3177bfcd01fc97fe667c273b8a43d"
  url:    "http://admin.nowapp.cn/"
  callback: "http://admin.nowapp.cn/syncs/qq/callback"
