development:
  key:    "92827868"
  secret: "0c802e26dc68ab541ad7dcff2d94d1b3"
  url:    "http://ruby_general_admin.dev/"
  callback: "http://ruby_general_admin.dev/syncs/sina/callback"
production:
  key:    "92827868"
  secret: "0c802e26dc68ab541ad7dcff2d94d1b3"
  url:    "http://admin.nowapp.cn"
  callback: "http://admin.nowapp.cn/syncs/sina/callback"
